<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Excepciones</title>

    <link rel="alternate" href="https://campusempresa.com/mod/cplusplus/07-02-exception-handling" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/mod/cplusplus/07-02-exception-handling" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/mod/cplusplus/07-02-exception-handling" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="/js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body >
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-12 col-md-8 p-2 p-md-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png"></a>
			</h1>
		</div>
		<div class="col-12 col-md-4 p-2 p-md-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-2 p-md-0 m-0 text-end">
										<a href="https://enterprisecampus.net/mod/cplusplus/07-02-exception-handling" class="px-2">EN</a></b>
				|
				<b class="px-2">ES</b>
				|
				<a href="https://campusempresa.cat/mod/cplusplus/07-02-exception-handling" class="px-2">CA</a>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">El Proyecto</a>
				<a href="/about">Sobre nosotros</a>
				<a href="/contribute">Contribuir</a>
				<a href="/donate">Donaciones</a>
				<a href="/licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content">
								<div class='row navigation'>
	<div class='col-2'>
					<a href='07-01-templates' title="Plantillas">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
					<a href="./"><h2 style="text-decoration:underline">Manejo de Excepciones</h2></a>
			</div>
	<div class='col-2 text-end'>
					<a href='07-03-file-io' title="Entrada/Salida de Archivos">Siguiente &#x25BA;</a>
			</div>
</div>
<div class='content'><p>El manejo de excepciones es una característica fundamental en C++ que permite a los programadores gestionar errores y condiciones excepcionales de manera controlada. En este módulo, aprenderemos cómo utilizar las excepciones para mejorar la robustez y la fiabilidad de nuestros programas.</p>
</div><h1><p>Conceptos Clave</p>
</h1>
<div class='content'><ol>
<li><strong>Excepción</strong>: Un evento que ocurre durante la ejecución de un programa y que interrumpe el flujo normal de las instrucciones.</li>
<li><strong>Lanzar (throw)</strong>: La acción de generar una excepción.</li>
<li><strong>Capturar (catch)</strong>: La acción de manejar una excepción lanzada.</li>
<li><strong>Bloque try</strong>: Un bloque de código que contiene instrucciones que pueden lanzar excepciones.</li>
<li><strong>Bloque catch</strong>: Un bloque de código que maneja las excepciones lanzadas en el bloque try.</li>
</ol>
</div><h1><p>Estructura Básica del Manejo de Excepciones</p>
</h1>
<div class='content'><p>La estructura básica para el manejo de excepciones en C++ incluye los bloques <code>try</code>, <code>throw</code> y <code>catch</code>. A continuación se muestra un ejemplo simple:</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIC8vIEJsb3F1ZSBkZSBjw7NkaWdvIHF1ZSBwdWVkZSBsYW56YXIgdW5hIGV4Y2VwY2nDs24KICAgICAgICBpbnQgZGl2aXNvciA9IDA7CiAgICAgICAgaWYgKGRpdmlzb3IgPT0gMCkgewogICAgICAgICAgICB0aHJvdyAiRGl2aXNpw7NuIHBvciBjZXJvIG5vIHBlcm1pdGlkYSI7CiAgICAgICAgfQogICAgICAgIGludCByZXN1bHQgPSAxMCAvIGRpdmlzb3I7CiAgICAgICAgY291dCA8PCAiUmVzdWx0YWRvOiAiIDw8IHJlc3VsdCA8PCBlbmRsOwogICAgfSBjYXRjaCAoY29uc3QgY2hhciogZSkgewogICAgICAgIC8vIEJsb3F1ZSBkZSBjw7NkaWdvIHF1ZSBtYW5lamEgbGEgZXhjZXBjacOzbgogICAgICAgIGNvdXQgPDwgIkVycm9yOiAiIDw8IGUgPDwgZW5kbDsKICAgIH0KICAgIHJldHVybiAwOwp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int main() {
    try {
        // Bloque de c&oacute;digo que puede lanzar una excepci&oacute;n
        int divisor = 0;
        if (divisor == 0) {
            throw &quot;Divisi&oacute;n por cero no permitida&quot;;
        }
        int result = 10 / divisor;
        cout &lt;&lt; &quot;Resultado: &quot; &lt;&lt; result &lt;&lt; endl;
    } catch (const char* e) {
        // Bloque de c&oacute;digo que maneja la excepci&oacute;n
        cout &lt;&lt; &quot;Error: &quot; &lt;&lt; e &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h2><p>Explicación del Código</p>
</h2>
<div class='content'><ol>
<li><strong>Bloque try</strong>: Contiene el código que puede lanzar una excepción. En este caso, estamos verificando si el divisor es cero antes de realizar una división.</li>
<li><strong>throw</strong>: Si el divisor es cero, lanzamos una excepción con el mensaje &quot;División por cero no permitida&quot;.</li>
<li><strong>Bloque catch</strong>: Captura la excepción lanzada y maneja el error imprimiendo un mensaje.</li>
</ol>
</div><h1><p>Tipos de Excepciones</p>
</h1>
<div class='content'><p>En C++, se pueden lanzar y capturar diferentes tipos de excepciones, incluyendo tipos básicos como <code>int</code>, <code>char</code>, <code>double</code>, y tipos definidos por el usuario como clases y estructuras.</p>
</div><h2><p>Ejemplo con Diferentes Tipos de Excepciones</p>
</h2>
<div class='content'></div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKdm9pZCBjaGVja051bWJlcihpbnQgbnVtKSB7CiAgICBpZiAobnVtIDwgMCkgewogICAgICAgIHRocm93IG51bTsgLy8gTGFuemEgdW5hIGV4Y2VwY2nDs24gZGUgdGlwbyBpbnQKICAgIH0gZWxzZSBpZiAobnVtID09IDApIHsKICAgICAgICB0aHJvdyAiTsO6bWVybyBlcyBjZXJvIjsgLy8gTGFuemEgdW5hIGV4Y2VwY2nDs24gZGUgdGlwbyBjb25zdCBjaGFyKgogICAgfSBlbHNlIGlmIChudW0gPiAxMDApIHsKICAgICAgICB0aHJvdyAxLjA7IC8vIExhbnphIHVuYSBleGNlcGNpw7NuIGRlIHRpcG8gZG91YmxlCiAgICB9Cn0KCmludCBtYWluKCkgewogICAgdHJ5IHsKICAgICAgICBjaGVja051bWJlcigxNTApOwogICAgfSBjYXRjaCAoaW50IGUpIHsKICAgICAgICBjb3V0IDw8ICJFcnJvcjogTsO6bWVybyBuZWdhdGl2byAiIDw8IGUgPDwgZW5kbDsKICAgIH0gY2F0Y2ggKGNvbnN0IGNoYXIqIGUpIHsKICAgICAgICBjb3V0IDw8ICJFcnJvcjogIiA8PCBlIDw8IGVuZGw7CiAgICB9IGNhdGNoIChkb3VibGUgZSkgewogICAgICAgIGNvdXQgPDwgIkVycm9yOiBOw7ptZXJvIG1heW9yIHF1ZSAxMDAiIDw8IGVuZGw7CiAgICB9CiAgICByZXR1cm4gMDsKfQ=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

void checkNumber(int num) {
    if (num &lt; 0) {
        throw num; // Lanza una excepci&oacute;n de tipo int
    } else if (num == 0) {
        throw &quot;N&uacute;mero es cero&quot;; // Lanza una excepci&oacute;n de tipo const char*
    } else if (num &gt; 100) {
        throw 1.0; // Lanza una excepci&oacute;n de tipo double
    }
}

int main() {
    try {
        checkNumber(150);
    } catch (int e) {
        cout &lt;&lt; &quot;Error: N&uacute;mero negativo &quot; &lt;&lt; e &lt;&lt; endl;
    } catch (const char* e) {
        cout &lt;&lt; &quot;Error: &quot; &lt;&lt; e &lt;&lt; endl;
    } catch (double e) {
        cout &lt;&lt; &quot;Error: N&uacute;mero mayor que 100&quot; &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h2><p>Explicación del Código</p>
</h2>
<div class='content'><ol>
<li><strong>checkNumber</strong>: Función que lanza diferentes tipos de excepciones basadas en el valor del argumento <code>num</code>.</li>
<li><strong>Bloques catch</strong>: Capturan y manejan las excepciones de diferentes tipos (<code>int</code>, <code>const char*</code>, <code>double</code>).</li>
</ol>
</div><h1><p>Ejercicio Práctico</p>
</h1>
<div class='content'></div><h2><p>Ejercicio 1: Manejo de Excepciones en una Calculadora</p>
</h2>
<div class='content'><p>Escribe un programa que implemente una calculadora simple que maneje excepciones para las siguientes operaciones: suma, resta, multiplicación y división. El programa debe lanzar una excepción si se intenta dividir por cero.</p>
<h4>Solución</h4>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKZG91YmxlIGNhbGN1bGF0ZShkb3VibGUgYSwgZG91YmxlIGIsIGNoYXIgb3ApIHsKICAgIHN3aXRjaCAob3ApIHsKICAgICAgICBjYXNlICcrJzoKICAgICAgICAgICAgcmV0dXJuIGEgKyBiOwogICAgICAgIGNhc2UgJy0nOgogICAgICAgICAgICByZXR1cm4gYSAtIGI7CiAgICAgICAgY2FzZSAnKic6CiAgICAgICAgICAgIHJldHVybiBhICogYjsKICAgICAgICBjYXNlICcvJzoKICAgICAgICAgICAgaWYgKGIgPT0gMCkgewogICAgICAgICAgICAgICAgdGhyb3cgIkRpdmlzacOzbiBwb3IgY2VybyBubyBwZXJtaXRpZGEiOwogICAgICAgICAgICB9CiAgICAgICAgICAgIHJldHVybiBhIC8gYjsKICAgICAgICBkZWZhdWx0OgogICAgICAgICAgICB0aHJvdyAiT3BlcmFkb3Igbm8gdsOhbGlkbyI7CiAgICB9Cn0KCmludCBtYWluKCkgewogICAgZG91YmxlIG51bTEsIG51bTI7CiAgICBjaGFyIG9wOwogICAgY291dCA8PCAiSW5ncmVzZSBkb3MgbsO6bWVyb3MgeSB1biBvcGVyYWRvciAoKywgLSwgKiwgLyk6ICI7CiAgICBjaW4gPj4gbnVtMSA+PiBudW0yID4+IG9wOwoKICAgIHRyeSB7CiAgICAgICAgZG91YmxlIHJlc3VsdCA9IGNhbGN1bGF0ZShudW0xLCBudW0yLCBvcCk7CiAgICAgICAgY291dCA8PCAiUmVzdWx0YWRvOiAiIDw8IHJlc3VsdCA8PCBlbmRsOwogICAgfSBjYXRjaCAoY29uc3QgY2hhciogZSkgewogICAgICAgIGNvdXQgPDwgIkVycm9yOiAiIDw8IGUgPDwgZW5kbDsKICAgIH0KCiAgICByZXR1cm4gMDsKfQ=="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

double calculate(double a, double b, char op) {
    switch (op) {
        case '+':
            return a + b;
        case '-':
            return a - b;
        case '*':
            return a * b;
        case '/':
            if (b == 0) {
                throw &quot;Divisi&oacute;n por cero no permitida&quot;;
            }
            return a / b;
        default:
            throw &quot;Operador no v&aacute;lido&quot;;
    }
}

int main() {
    double num1, num2;
    char op;
    cout &lt;&lt; &quot;Ingrese dos n&uacute;meros y un operador (+, -, *, /): &quot;;
    cin &gt;&gt; num1 &gt;&gt; num2 &gt;&gt; op;

    try {
        double result = calculate(num1, num2, op);
        cout &lt;&lt; &quot;Resultado: &quot; &lt;&lt; result &lt;&lt; endl;
    } catch (const char* e) {
        cout &lt;&lt; &quot;Error: &quot; &lt;&lt; e &lt;&lt; endl;
    }

    return 0;
}</pre></div><div class='content'></div><h2><p>Explicación del Código</p>
</h2>
<div class='content'><ol>
<li><strong>calculate</strong>: Función que realiza la operación aritmética basada en el operador proporcionado. Lanza excepciones si se intenta dividir por cero o si se proporciona un operador no válido.</li>
<li><strong>Bloque try</strong>: Llama a la función <code>calculate</code> y maneja cualquier excepción lanzada.</li>
<li><strong>Bloque catch</strong>: Captura y maneja las excepciones lanzadas por la función <code>calculate</code>.</li>
</ol>
</div><h1><p>Resumen</p>
</h1>
<div class='content'><p>En esta sección, hemos aprendido los conceptos básicos del manejo de excepciones en C++, incluyendo cómo lanzar y capturar excepciones utilizando los bloques <code>try</code>, <code>throw</code> y <code>catch</code>. También hemos visto ejemplos prácticos y un ejercicio para reforzar los conceptos aprendidos. El manejo adecuado de excepciones es crucial para escribir programas robustos y fiables, y es una habilidad esencial para cualquier programador de C++.</p>
</div><div class='row navigation'>
	<div class='col-2'>
					<a href='07-01-templates' title="Plantillas">&#x25C4;Anterior</a>
			</div>
	<div class='col-8 text-center'>
			</div>
	<div class='col-2 text-end'>
					<a href='07-03-file-io' title="Entrada/Salida de Archivos">Siguiente &#x25BA;</a>
			</div>
</div>

			</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Aceptar</a>
    <a href="/cookies">Mas información</a>
</div>	

	</div>    
</body>
</html>
